### ISSUE TITLE
dev-desktop: automatically add git config username&email for all gh users

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/simpleinfra#112]
We can grab all this information from their profile (using the github email address that anonymizes your actual email address)

**Comment by oli-obk** [comment]
we could scrape the info from the mailmap? XD

**Comment by pietroalbini** [comment]
Also see https://github.com/rust-lang/simpleinfra/pull/110

Not sure how much of a problem users manually setting it would be though.

**Comment by jdno** [comment]
https://github.com/rust-lang/simpleinfra/pull/110 has been merged and setting the Git username and email is now part of the `init.sh` script.
