### ISSUE TITLE
Less access for docs-rs background builder to s3

### ISSUE THREAD

**Issue by rylev** [rust-lang/simpleinfra#238]
Currently the background builder has [complete access to the s3 buckets](https://github.com/rust-lang/simpleinfra/blob/7951385dac72aa03682f9360eafd57fc866ab19e/terragrunt/modules/docs-rs/builder.tf#L35-L39) when it only need some write access (and no read access). 

I tried moving to only allowing the following actions: PutObject, PutObjectTagging, PutObjectAcl, CreateBucket, but this failed in a strange way. All artifacts were created and successfully uploaded to the s3. The logs only showed one error which simply stated that the library in question could not be documented (even though it clearly was successfully being done so). The only visible effect of this error was that the crate was not removed from the build queue.

**Comment by jyn514** [comment]
@rylev do you have a copy of the exact error message it printed?

**Comment by jyn514** [comment]
I suspect either `rustdoc_status` or `build_status` are getting set to `false` somehow, but not sure how that could be related to uploads.

**Comment by syphar** [comment]
there is a piece where the builder would also _read_ the bucket: 

when rebuilding a crate which was previously built without archive storage, we will clean the folder before uploading the archive.

**Comment by jyn514** [comment]
ahhhh, that's definitely it, good catch :) https://github.com/rust-lang/docs.rs/blob/f3cae4484c52b3ec64a4587842ac5df909406b83/src/storage/s3.rs#L288-L300

**Comment by jyn514** [comment]
I wonder if we should continue there even if we get an error deleting the old files. At that point we've already uploaded the files successfully and recorded it in the database, the error from S3 should be ok.

**Comment by syphar** [comment]
> I wonder if we should continue there even if we get an error deleting the old files. At that point we've already uploaded the files successfully and recorded it in the database, the error from S3 should be ok.

In general, yes, we could do that when it temporarily doesn't work. 

We still need the permissions to do it though, as long as we didn't rebuild everything, or repackage.
