### ISSUE TITLE
azure-configs: deploy fails when using Ubuntu 18.04

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/simpleinfra#31]
I updated Ubuntu image to 18.04 from 16.04 in this commit: https://github.com/rust-lang/libc/pull/1672/commits/92ae2be5115607ed677679af9504f9d5da03c653#diff-ff3fa021ec930a60c3eb9896d71cd851R15

But deploy fails in `azure-configs/static-websites.yml@rustinfra` template ([log](https://dev.azure.com/rust-lang2/libc/_build/results?buildId=1316&view=logs&j=c5397555-4577-58d8-d518-821f0664b4e0&t=abbe46b4-f5d0-5210-e2b0-c04bf6253ecc)).

Error says:
```
/bin/bash --noprofile --norc /home/vsts/work/_temp/0021839b-8dee-420a-83e4-9feb70c90223.sh
touch: cannot touch '/.nojekyll': Permission denied

##[error]Bash exited with code '1'.
```

I guess the template needs some tweaks when used on 18.04.
It isn't a big deal but it'd be great if we could use it on 18.04.

**Comment by pietroalbini** [comment]
Can you try if the `fix-azure` branch works?

**Comment by JohnTitor** [comment]
Uhm, it doesn't? (rust-lang/libc@b22922f7d86a7e5cccc7bc039a375b23d11436b4, [log](https://dev.azure.com/rust-lang2/libc/_build/results?buildId=1342&view=logs&j=c5397555-4577-58d8-d518-821f0664b4e0&t=abbe46b4-f5d0-5210-e2b0-c04bf6253ecc))

**Comment by pietroalbini** [comment]
You need to set `ref: refs/heads/fix-azure`, not `branch: fix-azure`. [docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#resources)

**Comment by JohnTitor** [comment]
Ah my bad, sorry! It seems to work well (rust-lang/libc@9726319a846fd68b23a8da636989b41aeff1d291).

**Comment by pietroalbini** [comment]
Pushed the fix to master!

**Comment by JohnTitor** [comment]
Thanks for the quick fix!
