### ISSUE TITLE
Implement tooling to rollback a ECR service deployment

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/simpleinfra#32]
Currently, the way to rollback a service deployed to ECR is to push a new image and redeploy it, which can be unnecessarily slow.

ECR has support for [retagging an image without uploading it again](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-retag.html). We should develop a script that prompts which image the user wants to rollback, retags it as `latest` and forces a new ECS deployment.

**Comment by pepoviola** [comment]
Hi @pietroalbini, I can help with this script with some guidance.

**Comment by pietroalbini** [comment]
That's great! My idea for this is to create a small Python script (like `aws-creds.py` in the root of this repository) that:

1. Calls the ECR API to list the available images in the repository.
2. Asks for the image the user wants to roll back to.
3. Tags the image the user chose to `latest`, without downloading it.
4. Forces a new ECS deployment.

Note that you'll need an AWS account of your own to test this, and I'm not sure if everything is included in the free tier.

**Comment by pietroalbini** [comment]
@pepoviola are you still working on this?

**Comment by pepoviola** [comment]
Hi @pietroalbini, sorry about the delay. It's ok to use the [python sdk](https://aws.amazon.com/sdk-for-python/) to interact with aws?

Thx!

**Comment by pietroalbini** [comment]
@pepoviola I'd slightly prefer to shell out to awscli, to avoid potential issues with Python dependencies (the CLI outputs JSON anyway).

**Comment by pepoviola** [comment]
Hi @pietroalbini, I have the logic in place for:

1. Calls the ECR API to list the available images in the repository.
2. Asks for the image the user wants to roll back to.
3. Tags the image the user chose to latest, without downloading it.

How you are forcing `ecs` to re-deploy, creating a new task definition?

Thanks!

**Comment by pietroalbini** [comment]
@pepoviola we use this command:

```
aws ecs update-service --cluster rust-ecs-prod --service <service-name> --force-new-deployment
```

**Comment by pepoviola** [comment]
Great, thanks @pietroalbini. I will create a pr for review.

**Comment by pepoviola** [comment]
Hi @pietroalbini, can we close this issue?
Thx!

**Comment by pietroalbini** [comment]
Yep! Thanks!
