### ISSUE TITLE
Please update the format used for build config imports on Travis CI

### ISSUE THREAD

**Issue by svenfuchs** [rust-lang/simpleinfra#33]
`rust-lang` has been one of the early alpha adopters of our build config import feature.

Various repositories are still using an early format for build config sources:

```
owner/repo/path/to/file.yml
```

During the product development process this has been superseded by the format:

```
owner/repo:path/to/file.yml
```

The format has been publicly announced in Nov 2019 with the feature.

* https://docs.travis-ci.com/user/build-config-imports/
* https://blog.travis-ci.com/2019-11-11-build-config-imports

The format you are currently using is not available any more for public use, `rust-lang` is currently safelisted for this outdated format, so your imports continue to work. However, in future versions of the build config processing component will not be able to support this.

Please update `.travis.yml` files that are importing config sources using the outdated format to use the new format:

* https://github.com/rust-lang/async-book/blob/master/.travis.yml
* https://github.com/rust-lang/compiler-team/blob/master/.travis.yml
* https://github.com/rust-lang/polonius/blob/master/.travis.yml
* https://github.com/rust-lang/rfcs/blob/master/.travis.yml
* https://github.com/rust-lang/rust-forge/blob/master/.travis.yml
* https://github.com/rust-lang/rust-log-analyzer/blob/master/.travis.yml
* https://github.com/rust-lang/thanks/blob/master/.travis.yml
* https://github.com/rust-lang/unsafe-code-guidelines/blob/master/.travis.yml
* https://github.com/rust-lang/unsafe-code-guidelines/blob/master/.travis.yml
* https://github.com/rust-lang/wg-traits/blob/master/.travis.yml

Pretty sure I'm missing other places ...

Also mentioned on:

* https://github.com/rust-lang/infra-team/blob/master/guidelines/static-websites.md
* https://github.com/rust-lang/simpleinfra/blob/master/README.md

Btw, if you are importing a single config source only then you can specify it as a string (as opposed to a sequence of strings)

```
import: rust-lang/simpleinfra:travis-configs/static-websites.yml
```

The sequence you have will work just fine of course, too:

```
import: 
- rust-lang/simpleinfra:travis-configs/static-websites.yml
```

**Comment by pietroalbini** [comment]
Thanks for reporting this!

I'll go over the repositories in the next few days to migrate everything to the new syntax.

**Comment by svenfuchs** [comment]
just to be sure ... the format for referencing file in foreign repos is:

```
owner/repo:path/to/file.yml
```

i am seeing something trying to reference:

```
rust-lang/rust-forge:rust-lang/simpleinfra/travis-configs/static-websites.yml
```

which i believe should be:

```
rust-lang/simpleinfra:travis-configs/static-websites.yml
```

**Comment by pietroalbini** [comment]
I believe we updated all the users of the shared snippets in our organization, so let's close this. Thanks for the report!

By the way, I haven't found the repository with the configuration you mentioned in https://github.com/rust-lang/simpleinfra/issues/33#issuecomment-600775272. Do you have the name of the repository on hand?

**Comment by svenfuchs** [comment]
@pietroalbini ah, sorry, i have missed your last comment. no, i do not have that repo available any more. i suppose it may have been coming from a fork, or something trying things out.

i'll keep an eye out and notify them myself (or get back here) if i spot it again.

thanks a lot for taking care of this!

❤️
