### ISSUE TITLE
Spurious network errors for `index.crates.io`

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#341]
We've received reports in Zulip that GitHub Actions sometimes fail with a network error when trying to download crates. Requests to `index.crates.io` time out, causing the builds to fail:

```
Run cargo build
    Updating crates.io index
warning: spurious network error (3 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
warning: spurious network error (2 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
warning: spurious network error (1 tries remaining): [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
error: failed to get `syn` as a dependency of package `serde_derive v1.0.183`
    ... which satisfies dependency `serde_derive = "=1.0.183"` of package `serde v1.0.183`
    ... which satisfies dependency `serde = "^1.0"` of package `backtrace v0.3.68 (D:\a\backtrace-rs\backtrace-rs)`
    ... which satisfies path dependency `backtrace` of package `cpp_smoke_test v0.1.0 (D:\a\backtrace-rs\backtrace-rs\crates\cpp_smoke_test)`

Caused by:
  failed to query replaced source registry `crates-io`

Caused by:
  download of 3/s/syn failed

Caused by:
  failed to download from https://index.crates.io/3/s/syn

Caused by:
  [28] Timeout was reached (Operation too slow. Less than 10 bytes/sec transferred the last 30 seconds)
Error: Process completed with exit code 1.
```

The failures so far always fail on the `syn` crate, but the given URL `https://index.crates.io/3/s/syn` works when testing locally.

## Examples

- https://github.com/rust-lang/backtrace-rs/actions/runs/5843021242/job/15844742707
- https://github.com/rust-lang/backtrace-rs/actions/runs/5843021242/job/15844741326
- https://github.com/rustls/rustls/actions/runs/5807199354/job/15741584111

## References

- [crates.io spurious network errors](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/crates.2Eio.20spurious.20network.20errors) topic in `t-infra` on Zulip
- [Timeout was reached](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/Timeout.20was.20reached) topic in `t-crates-io` on Zulip
- [Timeout investigation](https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/timeout.20investigation) topic in `t-cargo` on Zulip

**Comment by jonathanpallant** [comment]
See also https://github.com/ferrous-systems/rust-exercises/actions/runs/5967326186/job/16188788089

**Comment by Mark-Simulacrum** [comment]
One theory I brought up in https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/repeated.20errors.20in.20fetching.20.60syn.60 is that Cargo doesn't seem to close the TCP connection when retrying, which means that we're almost certainly hitting the same CloudFront server on all the retries. I think it would be worth seeing if we can change the implementation to re-open the connection (ideally also re-poking DNS) to try to get a different answer.

**Comment by jdno** [comment]
The discussion in https://rust-lang.zulipchat.com/#narrow/stream/246057-t-cargo/topic/timeout.20investigation suggests that the problem might be an issue with curl < 8.1 and Rust < 1.72.

**Comment by jdno** [comment]
We haven't received any new reports about this since September and there is been no further discussion on Zulip. I'm going to close the issue under the assumption that this was an issue with a specific version of curl. A workaround is available in the linked Zulip thread above.
