### ISSUE TITLE
Redirect minor versions to latest patch

### ISSUE THREAD

**Issue by jdno** [rust-lang/simpleinfra#360]
We got [a request on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Docs.20redirect.20minor.20versions.20to.20latest.20patch) to redirect requests for the documentation from the minor version (e.g. https://doc.rust-lang.org/1.65/std/boxed/struct.Box.html) to the latest patch for that version (e.g. https://doc.rust-lang.org/1.65.0/std/boxed/struct.Box.html).

The reason is that the first URL does not exist and will return `HTTP 404 Not Found`, while the latter works fine.

The CloudFront distribution is configured [here](https://github.com/rust-lang/simpleinfra/blob/master/terragrunt/modules/release-distribution/cloudfront-doc.tf) and is already using a [Lambda router](https://github.com/rust-lang/simpleinfra/blob/master/terragrunt/modules/release-distribution/lambdas/doc-router/index.js) to issue some redirects.

**Comment by MarcoIeni** [comment]
how do we get the latest patch from the edge function?
Either we hardcode it (it seems a waste of time) or we do an HTTP call somewhere but it seems a waste of resource.

I think the easiest solution is just to append `.0` and live with it.
I don't think that docs are going to change dramatically from patch to patch.

What do you think?

**Comment by MarcoIeni** [comment]
Also another doubt: we don't need to edit fastly code to make this change right? From a quick look it seems that the doc router is only on cloudfront 👍

**Comment by jdno** [comment]
> how do we get the latest patch from the edge function?

This question is the reason why no one has started working on this yet. 😅

I don't think we have a good solution for this. We _could_ fetch it from the function by doing an HTTP call, but we should avoid that since it will very negatively impact response times. We _could_ hard-code the releases in the function and just look up the latest patch version for each minor version, but that would need to be updated with every release.

Doing some quick math on the GitHub releases for `rust-lang/rust`, it seems that out of ~130 releases only 34 were a patch. So it feels kinda reasonable to default to `.0`, although ideally we'd have a "you are viewing outdated documentation" banner. But I guess that's a feature request for the rustdoc team.

**Comment by jdno** [comment]
> From a quick look it seems that the doc router is only on cloudfront 👍

That is correct. 👍  Only `static.crates.io` and `static.rust-lang.org` are served through Fastly right now.

**Comment by MarcoIeni** [comment]
I'm closing this because https://github.com/rust-lang/simpleinfra/pull/612 was merged and deployed.

I don't think there's a way to redirect to the latest patch that doesn't involve performance penalty or maintenance burden and the benefits are not worthy.
